// End-to-end tests for `Translator::translate`, grouped by feature area.
mod arrays;
mod bindings;
mod check;
mod classes;
mod clone_move;
mod console;
mod control_flow;
mod destructuring;
mod fmt;
mod globals;
mod math;
mod modules;
mod narrowing;
mod number_methods;
mod operators;
mod runtime_deps;
mod strings;
mod types;
