#!/usr/bin/env node
// Regenerates `crates/dashscript/tests/conformance/data/bcd-catalog.json` —
// the ES built-in API *catalog* auto-derived from `@mdn/browser-compat-data`.
//
// This file is coverage-gap data only: each entry is `{ id, category, source }`
// with no fixture (bcd tells you an API *exists*, never how to *call* it). The
// conformance runner records these as `untested` — they show which ES APIs the
// extracted translator-tests fixtures do not yet exercise. Fixtures themselves
// come from translator/tests (see extract-tests.mjs), not from bcd.
//
// Run after `pnpm install` (devDependency) at the repo root:
//   node scripts/sync-bcd.mjs

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const bcd = require("@mdn/browser-compat-data");

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(
  __dirname,
  "..",
  "crates",
  "dashscript",
  "tests",
  "conformance",
  "data",
  "bcd-catalog.json",
);

const builtins = bcd.javascript.builtins;

// Only built-ins in DashScript's scope; RegExp/Date/Promise/Map/Set/ArrayBuffer/
// ... are irrelevant to a Rust transpiler and would only add noise.
const SCOPE = {
  Array: "arrays",
  String: "strings",
  Math: "math",
  Number: "globals",
  Object: "globals",
};

// Structural members, not callable APIs.
const SKIP = new Set(["length", "name", "prototype", "displayName"]);

const features = [];
const seen = new Set();
function add(id, category) {
  if (seen.has(id)) return;
  seen.add(id);
  features.push({ id, category, source: "bcd" });
}

for (const [B, category] of Object.entries(SCOPE)) {
  const node = builtins[B];
  if (!node) continue;
  for (const [m, d] of Object.entries(node)) {
    if (m === "__compat" || m.startsWith("@@") || m === B || SKIP.has(m)) continue;
    if (!d || typeof d !== "object" || !d.__compat) continue;
    add(`${B.toLowerCase()}.${m}`, category);
  }
}

for (const fn of ["parseInt", "parseFloat", "isNaN", "isFinite", "encodeURI", "decodeURI"]) {
  if (builtins[fn]?.__compat) add(`global.${fn}`, "globals");
}
// Constructors used as global conversion functions.
for (const c of ["Number", "String", "Boolean"]) add(`global.${c}`, "globals");

const doc = {
  _comment:
    "Auto-generated by `scripts/sync-bcd.mjs` from @mdn/browser-compat-data. DO NOT edit by hand. Coverage-gap catalog only — no fixtures (bcd lists APIs, not call sites). The runner marks every entry `untested`; fixtures live in tests-fixtures.json (extracted from translator/tests).",
  features,
};
writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`sync-bcd: wrote ${features.length} catalog entries to ${OUT}`);
